steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/shopify-pipeline:$COMMIT_SHA', '.']
    dir: 'onboarding'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/shopify-pipeline:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'shopify-pipeline'
      - '--image'
      - 'gcr.io/$PROJECT_ID/shopify-pipeline:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'  # Private access only
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/shopify-pipeline:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY