steps:
  # Build the container image from parent directory using the Dockerfile in onboarding/
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/shopify-onboarding:$COMMIT_SHA', '-f', 'onboarding/Dockerfile', '.']
    # Note: Building from parent directory to include both onboarding/ and historical/

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/shopify-onboarding:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'shopify-onboarding'
      - '--image'
      - 'gcr.io/$PROJECT_ID/shopify-onboarding:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=happyweb-340014'

images:
  - 'gcr.io/$PROJECT_ID/shopify-onboarding:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY